modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}"
license="LGPL-3.0-or-later (code) + All Rights Reserved (assets) — see LICENSE.md"

[[mods]]
modId = "and"
version="${version}"
displayName = "Armed N' Dangerous"
authors = "MiraDev, Andr0medaDev"
description = '''An extension mod for Just Enough Guns! Please report any bugs you experienced through our GitHub page or in MigaMi's Discord Server!'''

[[dependencies.and]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.and]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.and]]
modId="jeg"
mandatory=true
versionRange="[0.14.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.and]]
modId="framework"
mandatory=true
versionRange="[0.7.8,)"
ordering="NONE"
side="BOTH"

[[dependencies.and]]
modId="geckolib"
mandatory=true
versionRange="[4.4.4,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "and.mixins.json"
